name: Docker Image CI

on: [push]

jobs:
  linux:
    name: Jupyter Cling
    runs-on: ubuntu-latest
    strategy:
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Jupyter Cling
      run: docker build . --file Dockerfile -t cpp-cling:latest
